### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TBedu**
Modified inappropriate areas in README.md

### CODE REVIEW

**Comment by Jannyboy11** [comment]
This is incorrect, MC 1.21 is no longer supported.

**Comment by TBedu** [comment]
If that's the case, you should delete 1.20.1 located at the end of the table

**Comment by Jannyboy11** [comment]
Hm, I should remove the 1.21 column from the other table then.

**Comment by Jannyboy11** [comment]
Fixed by 344345df294b5c1e558361d533c5a31506335cbb

**Pull request closed without merging**
